#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on Fri 06/19/2020 ... */ 
#define XMLRPC_C_VERSION "1.51.6" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 51 
#define XMLRPC_VERSION_POINT 6 
#endif 
